before_install:
  #This is a temporary workaround a rubygems bug! Remove later
  #see: https://github.com/bundler/bundler/issues/2784 & https://github.com/rubygems/rubygems/pull/763
  - gem update --system 2.1.11
  - gem --version
language: ruby
script: bundle exec rake --verbose --trace
bundler_args: --without development
matrix:
  allow_failures:
      - rvm: ruby-head
rvm:
  - jruby-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head