language: ruby
script: bundle exec rake --verbose --trace
bundler_args: --without development
matrix:
  allow_failures:
      - rvm: ruby-head
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
